### ISSUE TITLE
코드 완성

### ISSUE THREAD

**Issue by hoonski** [hoonski/O8_CardNews#1]
완전한 결과물이 나올 때 까지 계속 수정하고 완성

**Comment by hoonski** [comment]
로딩화면 추가 및 CCL추가

**Comment by rabbitew** [comment]
![start_image](https://user-images.githubusercontent.com/29935149/33305066-a22d272e-d44f-11e7-8fb9-0da0576a70e7.png)

핸드폰 화면 크기로 만든거!

**Comment by rabbitew** [comment]
![start_image2](https://user-images.githubusercontent.com/29935149/33305089-c6f5ab9e-d44f-11e7-836b-93d77d468e8f.png)
이건 상단바랑 밑에 버튼바(?) 크기 고려해서 만든거얌

**Comment by hoonski** [comment]
넵 해보고 올릴게용

**Comment by hoonski** [comment]
![2017-11-28 3 25 34](https://user-images.githubusercontent.com/30435278/33305222-685472d6-d450-11e7-94b5-fff8bf321c09.png)

**Comment by rabbitew** [comment]
굳!

**Comment by hoonski** [comment]
라이선스 보여주는 버튼 위치 어디로 할지, 버튼 이미지 좀 만들어줘

**Comment by ChaeLinYeo** [comment]
![2](https://user-images.githubusercontent.com/29560815/33306056-2438b8ce-d454-11e7-9901-73ce4193a2ef.png)
왼쪽에 세로버튼으로?

**Comment by rabbitew** [comment]
오오 좋댜

**Comment by hoonski** [comment]
![2017-11-28 4 02 43](https://user-images.githubusercontent.com/30435278/33306359-9a969ae4-d455-11e7-9525-d9e9dda068b0.png)

저거 넣어서 이렇게 돼

**Comment by hoonski** [comment]
메인 내용 수정하고 추가해서 사용자 가이드 이미지 교체만 남음

**Comment by hoonski** [comment]
수정한 이미지 모두 코드에 등록 완료 
코드 완성

**Comment by hoonski** [comment]
메인화면 이미지, 가이드 버튼 이미지 등 이미지 수정필요

**Comment by hoonski** [comment]
![2017-12-03 2 30 10](https://user-images.githubusercontent.com/30435278/33522724-e23563d2-d836-11e7-8e17-b144ef550810.png)
![2017-12-03 2 31 33](https://user-images.githubusercontent.com/30435278/33522725-e2696984-d836-11e7-9ee3-e725303d0777.png)
![Uploading 스크린샷 2017-12-03 오후 2.30.58.png…]()
하나 골라 주세요 메인화면

**Comment by xodh** [comment]
두번째 하늘하늘한게 좋은거 같아 일단 그걸로 메뉴얼사진 만들어서 보내줄께!

**Comment by xodh** [comment]
![image](https://user-images.githubusercontent.com/26317093/33524462-1e6460cc-d861-11e7-8000-112dbae98692.png)
![image](https://user-images.githubusercontent.com/26317093/33524468-280c1d0e-d861-11e7-9094-5eee475455dc.png)
![image](https://user-images.githubusercontent.com/26317093/33524471-2c64d120-d861-11e7-9fdf-44610f461403.png)
![image](https://user-images.githubusercontent.com/26317093/33524477-42d22fac-d861-11e7-91d9-f9a0ebb34130.png)
![image](https://user-images.githubusercontent.com/26317093/33524488-76afdf7c-d861-11e7-98e5-c0de8977decf.png)

**Comment by xodh** [comment]
![image](https://user-images.githubusercontent.com/26317093/33524494-85e1c7da-d861-11e7-91e6-2d51bdb043b1.png)
이렇게 원한거 였나?

**Comment by ChaeLinYeo** [comment]
아 그럼 홍보포스터 메인도 바꿀까? 새로 만든 사진으루?

**Comment by ChaeLinYeo** [comment]
![default](https://user-images.githubusercontent.com/29560815/33526429-c730c308-d884-11e7-8b50-6c9cfe883a9a.png)

요렇게?

**Comment by xodh** [comment]
![image](https://user-images.githubusercontent.com/26317093/33546595-c82726c6-d924-11e7-84fd-befd9a7115ef.png)
옥에티 발견해서 수정정

**Comment by hoonski** [comment]
사용자 메뉴얼 사진 전부 수정했어~

**Comment by hoonski** [comment]
완성본 깃헙에 올렸어
