### ISSUE TITLE
개발자 가이드 만들기

### ISSUE THREAD

**Issue by hoonski** [hoonski/O8_CardNews#2]
개발자 가이드

**Comment by Ochodus** [comment]
![image](https://user-images.githubusercontent.com/31723165/33308493-faa42b42-d45d-11e7-919a-ecad88900ea7.png)

![image](https://user-images.githubusercontent.com/31723165/33308498-0570d944-d45e-11e7-9b15-bc98e67ac296.png)

개발환경에 대한 요구 사양
저장경로랑 저장파일이름 설정 하는 것에 대한 방법 
그 외에 url 변경이나 기타 개발 가능 사항 추가 예정

설명을 한글로 적는게 더 나을까요?

**Comment by xodh** [comment]
영어로 적을 수 있으면 영어가 좋은 것 같아
내용도 잘 채워진 것 같고 좋네!
얼추 완성되면 파일 공유 부탁해 ~

**Comment by hoonski** [comment]
근데 굳이 안바꿔도 될거같아 
할 수 있으면 하고 그냥 그렇게 마무리만 해주면 될거같아

**Comment by Ochodus** [comment]
개발자 가이드 "Developer Guide.md"로 업로드 했어 수정할 거나 추가할 거 있는지 확인해줘~

**Comment by xodh** [comment]
오 좋아. 잘 만들었네

**Comment by ChaeLinYeo** [comment]
수고했어!!

**Comment by hoonski** [comment]
굳굳
