### ISSUE TITLE
발표자료 만들기

### ISSUE THREAD

**Issue by hoonski** [hoonski/O8_CardNews#3]
프로젝트 발표 자료 준비

**Comment by hoonski** [comment]
[OS-수정한 내용.docx](https://github.com/hoonski/O8_CardNews/files/1508817/OS-.docx)
기존의 코드에서 추가되거나 수정한 내용 정리

**Comment by xodh** [comment]
[PT초안.pptx](https://github.com/hoonski/O8_CardNews/files/1524699/PT.pptx)

**Comment by xodh** [comment]
[PT두번째.pptx](https://github.com/hoonski/O8_CardNews/files/1526742/PT.pptx)

**Comment by ChaeLinYeo** [comment]
혹시 사후 관리라고 적혀있는 부분은 뭐야..?

**Comment by ChaeLinYeo** [comment]
홍보는 처음에 페이스북 blueprint를 통해 마케팅 과정별로 공부할 계획이었음. 하지만 페이스북 광고는 하루에 팔천얼마...(은우가 확인했었는데 맞는지 확인해줘...)정도의 부담되는 금액을 지불해야 했음. 차선책으로 앱의 홍보 포스터를 제작하여 페이스북 페이지, 그리고 트위터 계정을 만들어 게시했음.

**Comment by ChaeLinYeo** [comment]
이미지 회전 기능을 구현하지 못해 해상도 높은 사진이 돌아가는 문제를 해결하지 못한 점이 아쉽지만 뉴스더보기나 앱 사용 가이드 등 사용자의 편의성을 위한 다양한 편의성이 증대되었다고 생각한다..? 회전기능은 굳이 질문 나오지 않는 이상 언급 안하는게 좋을거같지만 일단은...

**Comment by xodh** [comment]
오 그렇군 좋아좋아 굳굳

**Comment by xodh** [comment]
사후 관리 말 그대로 이렇게 프로젝트 끝나고 어떻게 처리할 지 적어놓으려구

**Comment by xodh** [comment]
[PT세번째.pptx](https://github.com/hoonski/O8_CardNews/files/1531278/PT.pptx)
거진 마무리

**Comment by xodh** [comment]
[PT최종본.pptx](https://github.com/hoonski/O8_CardNews/files/1533850/PT.pptx)
끝끝

**Comment by hoonski** [comment]
굳
