### ISSUE TITLE
홍보 포스터 만들기

### ISSUE THREAD

**Issue by hoonski** [hoonski/O8_CardNews#5]
어플리케이션 홍보 포스터 만들기

**Comment by ChaeLinYeo** [comment]
홍보 포스터 제작 완료! 두가지 디자인 중 선택해주세요. 수정할 부분 있음 말해주세요
![2017-11-27 4 55 03](https://user-images.githubusercontent.com/29560815/33305068-a5a8106c-d44f-11e7-869b-d94f0a43f49c.png)
![2017-11-27 4 52 18](https://user-images.githubusercontent.com/29560815/33305079-b839935e-d44f-11e7-8bd4-5bc2a8926493.png)

**Comment by hoonski** [comment]
전 2번이 좋은거 같아요

**Comment by rabbitew** [comment]
난 1번...
육각형 다메요...

**Comment by xodh** [comment]
저도 2번이여

**Comment by Ochodus** [comment]
저도 2번이 괜찮아 보여요

**Comment by hoonski** [comment]
그럼 2번으로 합시다
