### ISSUE TITLE
README.md 파일 수정

### ISSUE THREAD

**Issue by hoonski** [hoonski/O8_CardNews#6]
다른 조의 파일을 가져왔기 때문에 리드미 파일 수정 필요

**Comment by xodh** [comment]
Credits 부분을 수정. 우린 편집을 위주로 했기에 Editor 라는 목차를 만들어 조원이름 삽입.
(조원분들 영어이름 남겨주세요)

Features 에 새로 추가된 기능들을 작성 -> Link to Another Card News , User Manual

Requirements 에 이거 추가하기 -> api 17 이상 , sdk 16.0.2

이렇게 수정 하면 될까요?

**Comment by rabbitew** [comment]
EunWoo Lee

**Comment by ChaeLinYeo** [comment]
ChaeLin Yeo
네 괜찮은 것 같아요.

**Comment by hoonski** [comment]
YoungHoon Kwon
sdk 26.0.2로 수정
괜찮은 것 같아

**Comment by Ochodus** [comment]
SeungChan Yu

**Comment by xodh** [comment]
![image](https://user-images.githubusercontent.com/26317093/33365321-3396754a-d52b-11e7-8834-8e23eba04763.png)
screenshots 항목에 이미지 추가했슴돠. 
Readme.md에 사진 교체하겠습니다.

**Comment by xodh** [comment]
아 Readme.md에 링크들 몇 개 수정해야 하는데 저희 라이센스 보여주는 링크랑 icon~되어있는 링크는 그대로 둘까요 지울까요?

**Comment by hoonski** [comment]
음 그건 그냥 놔두면 될꺼같은데??

**Comment by hoonski** [comment]
README 파일에 개발자 가이드 링크 같은 것도 넣어놓는게 좋을거같아

**Comment by xodh** [comment]
그럼 그거 넣구 개발자들 끼리 의견을 나누는 페이스북 페이지 링크도 같이 추가할 께

**Comment by xodh** [comment]
이미지 최종수정본으로 업로드 완료.

**Comment by xodh** [comment]
APK 부분 다운받는 것 지우도록 하겠음.
